# Retry settings
retry:
  max_attempts: 3
  delay: 5  # in seconds

# File Storage Paths
data_paths:
  directories:
    - "./backend/data/raw/"
    - "./backend/data/clean/"
  files:
    json: 
      - "./backend/data/raw/blog_posts.json"
      - "./backend/data/clean/cleaned_blog_posts.json"

# API settings
rsg:
  brief_url: "https://resolutestrategy.com/the-brief"
  scrape_url: "https://resolutestrategy.com"

# Logging settings
logging:
  level: "INFO"
  file: 
    - "./logs/app.log"
    - "./logs/error.log"
    - "./logs/blog.log"
    - "./logs/resolute_cleaner.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


# Fetch settings
fetch:
  batch_size: "30"
  max_workers: "4"

# Processing settings
processing:
  batch_size: 50
  keywords_to_extract: 10
  summary_keywords: 5
  max_workers: "30"
  request_delay: "0.25" 
